import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/auth_service.dart';
import '../services/api_client.dart';
import '../services/connectivity_service.dart';

const _trackingMethods = [
  ('none', 'None (quantity-based)'),
  ('serial', 'Serial Number'),
  ('imei', 'IMEI'),
];

/// Add/edit form for a Product - matches the web app's Add Product dialog fields
/// (name, brand, barcode, category, tracking method, cost/selling price). SKU is
/// always auto-generated by the backend, never entered here.
class ProductFormScreen extends StatefulWidget {
  final Map<String, dynamic>? existing;
  const ProductFormScreen({super.key, this.existing});

  @override
  State<ProductFormScreen> createState() => _ProductFormScreenState();
}

class _ProductFormScreenState extends State<ProductFormScreen> {
  late final _name = TextEditingController(text: widget.existing?['name'] ?? '');
  late final _brand = TextEditingController(text: widget.existing?['brand'] ?? '');
  late final _barcode = TextEditingController(text: widget.existing?['barcode'] ?? '');
  late final _costPrice = TextEditingController(text: widget.existing?['cost_price']?.toString() ?? '');
  late final _sellingPrice = TextEditingController(text: widget.existing?['selling_price']?.toString() ?? '');
  late String _trackingMethod = widget.existing?['tracking_method'] ?? 'none';
  late int? _categoryId = widget.existing?['category'] as int?;
  List<Map<String, dynamic>> _categories = [];
  bool _saving = false;
  bool _loadingCategories = true;

  bool get _isEdit => widget.existing != null;
  static const _endpoint = '/api/products/products/';

  ApiClient get _api => context.read<AuthService>().api;

  @override
  void initState() {
    super.initState();
    _loadCategories();
  }

  Future<void> _loadCategories() async {
    try {
      final data = await _api.request('/api/products/categories/');
      final list = data is List ? data : (data as Map<String, dynamic>)['results'] as List<dynamic>;
      if (mounted) setState(() => _categories = list.cast<Map<String, dynamic>>());
    } catch (_) {
      // Offline or failed - category picker just shows "no category" only, non-fatal.
    } finally {
      if (mounted) setState(() => _loadingCategories = false);
    }
  }

  @override
  void dispose() {
    _name.dispose();
    _brand.dispose();
    _barcode.dispose();
    _costPrice.dispose();
    _sellingPrice.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (_name.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Product name is required.')));
      return;
    }
    final messenger = ScaffoldMessenger.of(context);
    final navigator = Navigator.of(context);
    setState(() => _saving = true);
    try {
      final body = {
        'name': _name.text.trim(),
        'brand': _brand.text.trim(),
        'barcode': _barcode.text.trim().isEmpty ? null : _barcode.text.trim(),
        'category': _categoryId,
        'tracking_method': _trackingMethod,
        'cost_price': _costPrice.text.trim().isEmpty ? '0' : _costPrice.text.trim(),
        'selling_price': _sellingPrice.text.trim().isEmpty ? '0' : _sellingPrice.text.trim(),
      };
      if (_isEdit) {
        // Editing an existing product needs a live round trip, unlike adding a new one -
        // not in the offline-capable tier, matching ContactFormScreen's edit path.
        await _api.request('$_endpoint${widget.existing!['id']}/', method: 'PATCH', body: body);
        messenger.showSnackBar(const SnackBar(content: Text('Product updated.')));
      } else {
        final online = context.read<ConnectivityService>().isOnline;
        final result = await _api.enqueueOrSend(
          isOnline: online,
          queueType: 'create_product',
          path: _endpoint,
          body: body,
          summary: 'New product - ${_name.text.trim()}',
        );
        messenger.showSnackBar(SnackBar(
          content: Text(result.queued ? 'Product saved offline - will sync automatically.' : 'Product added.'),
        ));
      }
      navigator.pop(true);
    } on ApiException catch (e) {
      messenger.showSnackBar(SnackBar(content: Text(e.message)));
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(_isEdit ? 'Edit Product' : 'Add Product')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          TextField(controller: _name, decoration: const InputDecoration(labelText: 'Name')),
          const SizedBox(height: 12),
          TextField(controller: _brand, decoration: const InputDecoration(labelText: 'Brand (optional)')),
          const SizedBox(height: 12),
          TextField(controller: _barcode, decoration: const InputDecoration(labelText: 'Barcode (optional)')),
          const SizedBox(height: 12),
          _loadingCategories
              ? const LinearProgressIndicator()
              : DropdownButtonFormField<int?>(
                  initialValue: _categoryId,
                  decoration: const InputDecoration(labelText: 'Category (optional)'),
                  items: [
                    const DropdownMenuItem<int?>(value: null, child: Text('No category')),
                    for (final c in _categories)
                      DropdownMenuItem<int?>(value: c['id'] as int, child: Text(c['name']?.toString() ?? '')),
                  ],
                  onChanged: (v) => setState(() => _categoryId = v),
                ),
          const SizedBox(height: 12),
          DropdownButtonFormField<String>(
            initialValue: _trackingMethod,
            decoration: const InputDecoration(labelText: 'Tracking Method'),
            items: _trackingMethods.map((t) => DropdownMenuItem(value: t.$1, child: Text(t.$2))).toList(),
            onChanged: (v) => setState(() => _trackingMethod = v ?? 'none'),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _costPrice,
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  decoration: const InputDecoration(labelText: 'Cost Price'),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: TextField(
                  controller: _sellingPrice,
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  decoration: const InputDecoration(labelText: 'Selling Price'),
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),
          FilledButton(
            onPressed: _saving ? null : _save,
            style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(48)),
            child: Text(_saving ? 'Saving...' : 'Save'),
          ),
        ],
      ),
    );
  }
}
